apiVersion: v1
kind: Service
metadata:
  name: mx-predict-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    # the label of the deployment must match this,
    # not the name
    app: mx-predict-app