apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mx-predict-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mx-predict-app
    spec:
      containers:
      - name: app1
        image: awsdeeplearningteam/mms_cpu
        command: ["mxnet-model-server"]
        args: ["start", "--mms-config", "/mxnet_model_server/mms_app_cpu.conf"]
        env:
        - name: AUTHOR
          value: app1
        ports:
        - containerPort: 8080