apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  # the rewrite rule will take your request like
  # curl test.sethah.com:80/squeezenet/predict
  # and change it forward it to the mx predict
  # service but it will rewrite the path from 
  # /squeezenet/predict to /, which is not good!
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: test.sethah.com
    http:
      paths:
      - backend:
          # take all traffic received by ingress
          # controller with hostname "test.sethah.com"
          # and path /squeezenet/predict and route that
          # to the service mx-predict-svc:80
          serviceName: mx-predict-svc
          servicePort: 80
        path: /squeezenet/predict